### ISSUE TITLE
测试发现用不了，到了跟踪整个画面卡爆了，然后，直接闪退的。。。

### ISSUE THREAD

**Issue by Dreamskya** [Tarrin/PyQt5_YoLoV5_DeepSort#2]

**Comment by Tarrin** [comment]
或许你可以上传一个视频吗？控制台的输出是怎么样的？还有你机器的配置？
我刚刚在我机子上跑了一下是没问题的...

**Comment by Dreamskya** [comment]
@Tarrin 方便加个QQ，方便交流下。694862446

**Comment by Dreamskya** [comment]
![图片](https://user-images.githubusercontent.com/31117684/102885502-67a76300-448e-11eb-901b-83a770b9a0ff.png)

**Comment by Dreamskya** [comment]
![c76fc7a3045a4ffbd47800531aec401](https://user-images.githubusercontent.com/31117684/102885591-91608a00-448e-11eb-9979-404a49749bc0.png)

**Comment by Dreamskya** [comment]
就这样卡死了，我的电脑配置是 影驰1660
