### ISSUE TITLE
进行本地视频检测的时候，帧率很慢怎么回事呢？

### ISSUE THREAD

**Issue by feifeiwei** [Tarrin/PyQt5_YoLoV5_DeepSort#3]
前端窗口显示的检测与跟踪结果视频很慢...

**Comment by Tarrin** [comment]
我在代码里面加了当qsize>1就会取出来一个，按理说视频应该是加速了的...你的CPU和GPU分别是什么型号？我好像默认处理图像的分辨率是1920*1080，不知道是不是分辨率太大了机器处理不过来？

**Comment by feifeiwei** [comment]
gpu是RTX2070，我调成LoadStreams进行数据后现在速度可以了， 但是跟踪和检测容易丢失，直接python track.py不会有这个问题...
